[package]
name = "io-uring"
version = "0.3.2"
authors = ["quininer <quininer@live.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/quininer/io-uring"
homepage = "https://github.com/quininer/io-uring"
documentation = "https://docs.rs/io-uring"
description = "The `io_uring` library for Rust."
categories = [ "asynchronous", "network-programming", "filesystem" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
exclude = [ "loom-ringbuf" ]

[features]
concurrent = [ "parking_lot" ]
unstable = []
overwrite = [ "bindgen" ]

[dependencies]
libc = "0.2"
bitflags = "1"
parking_lot = { version = "0.10", optional = true }

[build-dependencies]
bindgen = { version = "0.53", optional = true }

[dev-dependencies]
tempfile = "3"
anyhow = "1"
nix = "0.17"
lazy_static = "1"
socket2 = "0.3"
criterion = "0.3"
iou = "0.2"
slab = "0.4"

[package.metadata.docs.rs]
features = [ "concurrent", "unstable" ]

[[bench]]
name = "nop"
harness = false
