[package]
name = "linux-io-uring"
version = "0.0.5"
authors = ["quininer <quininer@live.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
repository = "https://github.com/quininer/linux-io-uring"
homepage = "https://github.com/quininer/linux-io-uring"
documentation = "https://docs.rs/linux-io-uring"
description = "The `io_uring` library for Rust."
categories = [ "asynchronous", "network-programming", "filesystem" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
exclude = [ "loom-ringbuf" ]

[features]
bindgen = [ "linux-io-uring-sys/bindgen" ]

[dependencies]
libc = "0.2"
bitflags = "1"
parking_lot = "0.10"

# Avoid leaking types from -sys because it is unstable.
linux-io-uring-sys = { version = "0.0.3", path = "linux-io-uring-sys" }

[dev-dependencies]
tempfile = "3"
anyhow = "1"
nix = "0.15"
lazy_static = "1"
socket2 = "0.3"
criterion = "0.3"
iou = "0.1"

[[bench]]
name = "nop"
harness = false
