[package]
name = "leot"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
	"linux-io-uring-sys",
	"linux-io-uring"
]

[dependencies]
libc = "*"
