[package]
name = "linux-io-uring-sys"
version = "0.1.0"
authors = ["quininer <quininer@live.com>"]
edition = "2018"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "*"
